### ISSUE TITLE
Display raw mouse movement / coordinates

### ISSUE THREAD

**Issue by claell** [Bluegrams/MPos#1]
I was looking for a tool to display the raw mouse coordinates in order to be able to calculate the actual (hardware) mouse DPI. Unfortunately there does not seem to be a tool available for this or not working (https://www.passmark.com/forum/other-software/3862-test-your-mouse-polling-rate-and-dpi).

Windows seems to offer an API to get those values: https://docs.microsoft.com/de-de/windows/desktop/DxTechArts/taking-advantage-of-high-dpi-mouse-movement#wm_input

This has the
> advantage to using WM_INPUT is that your game receives raw data from the mouse at the lowest level possible.

**Comment by alxnull** [comment]
Thanks for your suggestion, I'll look into this and see what I can do. Not sure how well processing raw input from C#/.NET works.
I will leave this open as a feature request. If you want to contribute something yourself, you're very welcome to open a PR.

**Comment by claell** [comment]
Thanks. Unfortunately I don't have time currently and am also not familiar with the language used for this tool, so probably I won't create a PR for this.

**Comment by claell** [comment]
Has this been implemented or wontfix?

**Comment by alxnull** [comment]
@claell Sorry, this has not been implemented.

**Comment by claell** [comment]
Alright, thanks for the update!
