### ISSUE TITLE
Only log selected data

### ISSUE THREAD

**Issue by shortyorty** [Bluegrams/MPos#3]
It would be great if the data log only included the information the user checked in the view menu. For instance, DPI information is logged even if it is deselected as a view option on the UI. This would help in cleaning up the amount of data in the log if only minor data is required (e.g. only mouse x,y, or only RGB values).

**Comment by alxnull** [comment]
Hi @shortyorty, thanks for the suggestion. This has just been implemented and will be released with the next version :)

**Comment by alxnull** [comment]
Now available in v.0.4.
