### ISSUE TITLE
[Feat Req] Configurable Position Data Structure

### ISSUE THREAD

**Issue by 4N7** [Bluegrams/MPos#6]
### Summary
This is a feature request; requesting the ability to configure how position data is structured. This would allow this software to be easily integrated into various workflows.

### Example
Position data is currently statically structured. If one needs to obtain many coordinates, extracting the needed data from this structure can be tedious. To ease the process, tools such as sed, grep, awk, ect can be used or the structure can be edited in source. However, not everyone is familiar with these methods.
```
Physical: {X=1234,Y=1234}\nRelative: {X=1234,Y=1234}
```

### Suggestion
A new menu/sub-menu with the option to configure data structure within a text box. The following variables would be available to the user `physicalX`, `physicalY`, `relativeX`, and `relativeY`. Other strings, that may assist the user's workflow, may also be added.

**Comment by alxnull** [comment]
Thanks for the suggestions. This has been added in MPos v.0.5. Go to the customization dialog (`Ctrl+,`) and select the tab "Data Format".
